@startuml
left to right direction
skinparam packageStyle rectangle

actor Utilisateur
actor Administrateur

usecase "Gérer les prêts" as UC_GererPrets
usecase "Voir ses prêts en cours" as UC_VoirSesPrets
usecase "Créer un prêt pour un utilisateur avec un produit" as UC_CreerPret

Utilisateur --> UC_VoirSesPrets
Administrateur --> UC_VoirSesPrets
Administrateur --> UC_CreerPret

UC_CreerPret --> UC_GererPrets

@enduml